### PR TITLE
Replaced favicon with a version using the new gwt logo.

### PR DESCRIPTION
**Pull request by foxylion**

### CODE REVIEW

**Comment by jDramaix** [comment]
@jasonlemay Could you check with Manon if this is the right favicon to use ?

**Comment by jasonlemay** [comment]
It's perfect

**Comment by jDramaix** [comment]
Thanks !

**Comment by tbroyer** [comment]
@jDramaix @foxylion We need a similar change to GWT proper for the CodeServer, the samples, and the WebAppCreator. They're in ICO format though.

```
$ git ls-files |grep favicon
dev/codeserver/java/com/google/gwt/dev/codeserver/favicon.ico
samples/dynatable/war/favicon.ico
samples/dynatablerf/src/main/webapp/favicon.ico
samples/hello/war/favicon.ico
samples/json/war/favicon.ico
samples/mail/war/favicon.ico
samples/mobilewebapp/src/main/webapp/favicon.ico
samples/showcase/war/favicon.ico
samples/validation/src/main/webapp/favicon.ico
user/src/com/google/gwt/user/tools/templates/sample/_warFolder_/favicon.icobin
```

**Comment by foxylion** [comment]
@tbroyer I submitted a patch to gerrit: https://gwt-review.googlesource.com/#/c/11520/

**Pull request merged**
