### PR TITLE
Updated "Related resources" video links

### PR DESCRIPTION
**Pull request by marcelstanley**
Replaced non-existent Google I/O links with YouTube valid ones.

[Review on Reviewable](https://reviewable.io/reviews/gwtproject/gwt-site/97)

### CODE REVIEW

**Comment by marcelstanley** [comment]
I signed it!

**Comment by manolo** [comment]
LGTM

**Comment by jDramaix** [comment]
Thanks for this contribution

**Comment by marcelstanley** [comment]
You're welcome!

**Pull request merged**
