### PR TITLE
Fix bad conversion of RPC.md

### PR DESCRIPTION
**Pull request by jDramaix**
Bug: issue [#9096](https://code.google.com/p/google-web-toolkit/issues/detail?id=9096)

### CODE REVIEW

**Comment by jDramaix** [comment]
@branflake2267 @tbroyer Same change but with one commit. 

@tbroyer Unfortunately I think we won't be able to keep the history as clean as it would be with gerrit... But as far as I'm concerned, it's not really a problem for the documentation

**Comment by tbroyer** [comment]
You can't have a "linear" history with pull requests, this is a compromise we accepted when migrating to GitHub (note that Gerrit was configured with a "merge if necessary" strategy, which is almost identical: Gerrit would have used fast-forwards when possible, when GitHub unconditionally creates merge commits).

BTW, why didn't you just rebased your branch to remove the extraneous merge commit and "push force" ?

**Comment by tbroyer** [comment]
I haven't checked in details but LGTM :shipit:

**Comment by jDramaix** [comment]
> BTW, why didn't you just rebased your branch to remove the extraneous merge commit and "push force" ?

Because it seems that having changed the origin to target github screws up a bit my local repo. So I took the decision to re-clone the repo form the github url and report the change (it's was to quickest solution for me :p)

**Pull request merged**
