### PR TITLE
Replace Pegdown with Commonmark

### LINKED ISSUE #332: Build the gwt-site with Maven doesn't work
Building with Maven only, as documented in the README doesn't work:

`mvn clean install -Pgrunt`

Instead I need to deactivate the tests:

`mvn clean install -Pgrunt -DskipTests`

### PR DESCRIPTION
**Pull request by zbynek**
Pegdown is no longer maintained, which will cause problems when upgrading build pipeline to Java 17.
Also it's nice to use an implemenntation of Markdown that is compatible with GH previews and IDE plugins -- commonmark seems to do quite well.

Three differences had to be handled in this PR though:
* code snippets are now delimited by backticks since indented snippets behaved differently in Pegdown and Commonmark. 
* Commonmark does not support typography replacements (`--` to en-dash, `---` to em-dash, quotes) out of the box, HTML entities can be used instead.
* no support for special definition list MD extension (only used by DevGuideI18nMessages) -- rewritten to HTML tags 

Fixes #332

### CODE REVIEW

**Comment by zbynek** [comment]
Preview at https://github.com/Vertispan/gwtproject.org

**Comment by niloc132** [comment]
The hosting for the link above is at https://www.gwtproject.org.vertispan.com/ - the contents from https://github.com/gwtproject/gwt-site-webapp/pull/13 is also included in that build.

**Review by craigmit — APPROVED** [review]
LGTM

**Comment by niloc132** [comment]
Updated to latest gwt-site-webapp main and this PR at https://www.gwtproject.org.vertispan.com/ - looking good to me.

**Review by niloc132 — APPROVED** [review]

**Pull request merged**
