### PR TITLE
Fix unescaped HTML

### PR DESCRIPTION
**Pull request by MALfunction84**
Using code formatting for "<div>" avoids line break and preserves readability.

**Edit:** Irony: see above. GitHub uses Markdown too. The above should read: "Using code formatting for '&lt;div&gt;' avoids line break and preserves readability."

[Review on Reviewable](https://reviewable.io/reviews/gwtproject/gwt-site/101)

### CODE REVIEW

**Comment by manolo** [comment]
Could you please sign the CLA like is indicated above

**Comment by MALfunction84** [comment]
I signed it!

**Comment by MALfunction84** [comment]
I'm confused. This page says the PR was merged, and there is a [merge commit](https://github.com/gwtproject/gwt-site/commit/5f113781e9853a7a24abb7369d20f26ba22392cd), but it doesn't show up in the [commits](https://github.com/gwtproject/gwt-site/commits/master) yet.

**Comment by manolo** [comment]
Yes I did push commit by mistake, so I rolled back master.
Just sign your CLA and I'll take care of merging it again.

**Comment by manolo** [comment]
I saw your comment that you signed it. Could you try to make some extra modification to the file so as we see what happens. Otherwise try opening another PR with the same modification, and we abandon this.

**Comment by MALfunction84** [comment]
I made another similar correction, but it didn't show up here, I think because it's already closed. Opened #105 which has both changes.

**Pull request merged**
