### PR TITLE
Fix 2 links in DevGuideCompilingAndDebugging.md

### PR DESCRIPTION
**Pull request by feedm3**
I think the first link did not work because auf the special character '?' and the second link had a typo. 

I  tested both links locally. They now work.

[Review on Reviewable](https://reviewable.io/reviews/gwtproject/gwt-site/128)

### CODE REVIEW

**Comment by feedm3** [comment]
CLA signed :+1:

**Comment by jDramaix** [comment]
Did you verify that those links were not referenced in other pages ?

**Comment by feedm3** [comment]
Forgot it, sorry. I found one reference and edited it

**Comment by feedm3** [comment]
CLA check should work. I pushed with another email (different PC) but resigned the CLA afterwards.

**Comment by jDramaix** [comment]
LGTM

**Comment by jDramaix** [comment]
Thanks

**Pull request merged**
