### PR TITLE
Update 'what's new' link on Overview page

### PR DESCRIPTION
**Pull request by azatsarynnyy**
Update 'what's new' section on Overview page with link to the latest GWT release

---

This change is [Reviewable](https://reviewable.io/reviews/gwtproject/gwt-site/206)

### CODE REVIEW

**Comment by jDramaix** [comment]
@azatsarynnyy Could you sign the CLA?

**Comment by azatsarynnyy** [comment]
I signed it!

**Comment by azatsarynnyy** [comment]
@jDramaix I've signed CLA
Thanks for the reminder

**Comment by jDramaix** [comment]
Thanks

**Pull request merged**
