### PR TITLE
point to GWT Eclipse plugin instead of GPE

### PR DESCRIPTION
**Pull request by elharo**
@branflake2267

---
This change is [Reviewable](https://reviewable.io/reviews/gwtproject/gwt-site/218)

### CODE REVIEW

**Comment by branflake2267** [comment]
It would be nice to drop all references of GPE in the GWT guides. And then implement one guide for IDE plugins, pointing to there location. And then let the IDE guides take over for specifics. 

@elharo thanks!

**Comment by branflake2267** [comment]
lgtm

**Comment by elharo** [comment]
Thanks @branflake2267 You'll need to merge this. I don't have write permissions.

**Comment by manolo** [comment]
Thanks
:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gwtproject/gwt-site/218#-:-Ke35-uZVGIeHj7bf46Z:bal51bs)*

**Pull request merged**
