### PR TITLE
s/wit/with

### PR DESCRIPTION
**Pull request by plaird-tutela**
Fix a typo.

[Review on Reviewable](https://reviewable.io/reviews/gwtproject/gwt-site/121)

### CODE REVIEW

**Comment by manolo** [comment]
@plaird-tutela do you mind to sign the gwt contributors  agreement so as we can merge this?

**Comment by jDramaix** [comment]
@plaird-tutela ping

**Comment by jDramaix** [comment]
@plaird-tutela last ping :)

**Comment by plaird-tutela** [comment]
Sorry about that, missed replying with "I signed under Tutela Technologies."

**Comment by jDramaix** [comment]
Thanks

**Pull request merged**
