### PR TITLE
Update DevGuideOrganizingProjects.md

### PR DESCRIPTION
**Pull request by a2g**
It could be inferred, from reading the instruction, that one should create a root package and client package side by side. "Within the src package, create a project root package and a client package."

---
This change is [Reviewable](https://reviewable.io/reviews/gwtproject/gwt-site/222)

### CODE REVIEW

**Comment by a2g** [comment]
I signed it!

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/markdown/doc/latest/DevGuideOrganizingProjects.md, line 106 at r1](https://reviewable.io:443/reviews/gwtproject/gwt-site/222#-Ke31xzAigRJHDxEc9zR:-Ke31xzAigRJHDxEc9zS:b-7byopn) ([raw file](https://github.com/gwtproject/gwt-site/blob/91ca9bd26ecedd144a4b74c8559c87b7f6c09472/src/main/markdown/doc/latest/DevGuideOrganizingProjects.md#L106)):*
> ```Markdown
>     *   war folder - your web app; contains static resources as well as compiled output
>     *   test folder - (optional) JUnit test code would go here
> 3.  Within the src package, create a project root package, and within that create a client package.
> ```

shouldn't be a comma after `within that`? 
Not a grammar expert, so not sure in English, but when translated to my language I feel like it's necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gwtproject/gwt-site/222)*

**Comment by manolo** [comment]
Seems like your CLA is not working, sometimes it happens if your github user is not linked to the email account you sign the CLA.

**Comment by tbroyer** [comment]
As a French, I'd only put a comma if there was a comma between the `and` and `within`: “and, within that, create…”. Otherwise “and within that create” sounds OK to me.

(oh my, every time I try to use Reviewable I'm reminded how much I hate it; so replying right in GitHub even if that means losing the context of the comment)

**Comment by manolo** [comment]
Ok, then leave it as it, but pls fix the CLA issue.

:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gwtproject/gwt-site/222#-:-KeNYt7hM6UanBKGkLDI:bt3d8g6)*

**Pull request merged**
