### PR TITLE
Fixed markup for bullets in Overview

### PR DESCRIPTION
**Pull request by rhmoller**

### CODE REVIEW

**Comment by rhmoller** [comment]
Hm not sure this fixes anything. Seems like the markdown preview at github works differently than the markdown rendering at gwtproject.org

If you look at this page, you will see that the bullets in the overview section are not rendered correctly.
http://www.gwtproject.org/doc/latest/DevGuideUiBinder.html

But if you look at the github preview the bullets are rendered correctly (also before my change)

https://github.com/gwtproject/gwt-site/blob/master/src/main/markdown/doc/latest/DevGuideUiBinder.md

**Comment by tbroyer** [comment]
I think the fix is actually to insert a blank line after line 39, before the first bullet. See http://spec.commonmark.org/0.17/#example-201

**Comment by jDramaix** [comment]
@tbroyer 's right. You have to insert a new line before the list item

**Comment by dankurka** [comment]
If you encouter such a problem with gwt-site just clone the project and locally run:

mvn clean install

After that you can find the whole site being generated into target/generated-site

**Comment by rhmoller** [comment]
Thank you. I cloned the project and built it. Julien and Thomas were right, the real fix is to add an empty line before the bullets.

**Comment by jDramaix** [comment]
Thanks for the patch !

**Pull request merged**
