### PR TITLE
added and updated the item-icon attribute

### PR DESCRIPTION
**Pull request by Toasbi**
in a previous pull(https://github.com/gwtproject/gwt-site/pull/157) i added the item-icon attribute in a wrong way.
to add an attribute on a element in ui binder it needs an empty value and has to look like this:
item-icon=""

to add an attribute on a widget in ui binder it has to look like this:
attributes="item-icon" 

the actual version wont compile because of this...
sorry for that!!

[Review on Reviewable](https://reviewable.io/reviews/gwtproject/gwt-site/164)

### CODE REVIEW

**Comment by jnehlmeier** [comment]
Looks like your commit 0cf8459 should be removed from this pull request, shouldn't it?

**Comment by manolo** [comment]
@Toasbi, please  can you squash all the commits in this PR into one and rebase with master ?

**Comment by tbroyer** [comment]
Just a note in passing: if you don't know how to rebase and squash, you can just use http://rebaseandsqua.sh
(but then, learn about `git rebase -i`)

**Comment by manolo** [comment]
Squashed manually and merged

**Pull request closed without merging**
