### PR TITLE
update the getting started page

### PR DESCRIPTION
**Pull request by vegegoku**
1- update the getting started to maven instead of ant.
2- update the GWT version in getting started to 2.8.1.
3- add a section for tbroyer maven archetype.

---
This change is [Reviewable](https://reviewable.io/reviews/gwtproject/gwt-site/250)

### CODE REVIEW

**Comment by vegegoku** [comment]
I signed it!

**Comment by vegegoku** [comment]
I signed it!

**Comment by vegegoku** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gwtproject/gwt-site/250#-:-KmiJrqQeT31lRl79dFJ:bnfp4nl)*

**Comment by vegegoku** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gwtproject/gwt-site/250)*

**Comment by tbroyer** [comment]
I, for one, **strongly** recommend **against** using webAppCreator with the _maven_ template.

Also, the instructions for my gwt-maven-archetypes have just changed; it would maybe be better to just link to them.

**Comment by vegegoku** [comment]
So then should i remove the part related to webAppCreator or just remove the part related to the maven template only.

and for the gwt-maven-archetypes i can just have the link to your github repository.

**Pull request closed without merging**
