### PR TITLE
Add steering committee meeting notes

### PR DESCRIPTION
**Pull request by aofner**
Add steering committee meeting notes from 2015 - 2016

---

This change is [Reviewable](https://reviewable.io/reviews/gwtproject/gwt-site/173)

### CODE REVIEW

**Comment by jnehlmeier** [comment]
I generally like it. @tbroyer do you think the committee can keep that up-to-date by making pull requests instead of (or in addition to) writing an online document?

**Comment by aofner** [comment]
Hi @jnehlmeier. If you accept the pull request - i will keep the page up to date and add all future meeting notes. So the core team can still use google docs.

**Comment by manolo** [comment]
I think is a big advance to have this info in gwtproject site, also it gives more visibility to SC actions. It shouldn't be a big effort to have the page updated.

**Comment by jDramaix** [comment]
@dankurka @tbroyer Are you ok with this ?

**Comment by tbroyer** [comment]
On principle, yes. Not sure if we should put the notes in the page, or link to them in Drive.

**Comment by jDramaix** [comment]
I'm more in favor to create a doc in Drive and put a link to the doc in the website. 
So that the steering committee could update the doc directly.

@tbroyer could you mention this point during the next SC ?

**Comment by jDramaix** [comment]
Any updates?

**Comment by jnehlmeier** [comment]
I kind of like the idea of @tbroyer that steering members would put their notes in a drive folder and we link to it, so the site does not need to be updated regularly.

**Comment by aofner** [comment]
If you prefer a list of links i will make a further pull request with following content:

Steering Commitee News

Meeting Notes 07/20/2016 (linked to google docs)
Meeting Notes 04/13/2016 (linked to google docs)
Meeting Notes 02/10/2016 (linked to google docs)
Meeting Notes 01/20/2016 (linked to google docs)
Meeting Notes 10/28/2015 (linked to google docs)
Meeting Notes 08/19/2015 (linked to google docs)
Meeting Notes 06/17/2015 (linked to google docs)
Meeting Notes 02/11/2015 (linked to google docs)

on page http://www.gwtproject.org/steering.html (after last paragraph)

OK?

**Comment by tbroyer** [comment]
We discussed this briefly at the last Steering Committee meeting… and I can't remember the outcome! IIRC, we settled on putting the notes directly into the gwt-site project, one webpage (markdown document) per meeting.

@jDramaix can you ping Bhaskar about this? (and sharing his notes ;-) )

**Comment by manolo** [comment]
do the author have to split this PR into the one md per meeting?
Ping @jdramaix, any news about those notes?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gwtproject/gwt-site/173#-:-Ke390C9JXFoqnw4Ipav:b2ns8el)*

**Comment by tbroyer** [comment]
Ping @niloc132

**Comment by niloc132** [comment]
Sorry about my delay on this - if there is no further discussion I'll merge this in 24 hrs, and then add another follow up patch with all 2017 meeting notes.

**Comment by aofner** [comment]
Added 07/20/2016 & 04/13/2016

**Pull request merged**
