### PR TITLE
Fix for grammar in buildui.md

### PR DESCRIPTION
**Pull request by Jackkoz**
[Review on Reviewable](https://reviewable.io/reviews/gwtproject/gwt-site/134)

### CODE REVIEW

**Comment by jDramaix** [comment]
@Jackkoz  Could you sign the CLA ?

**Comment by jDramaix** [comment]
@Jackkoz ping. CLA needs to be signed in order to merge this PR

**Comment by Jackkoz** [comment]
I signed it!

**Comment by jnehlmeier** [comment]
@jDramaix can you manually verify that CLA has been signed? Seems like Google Bot was on vacation on 1st Feb.

**Comment by Jackkoz** [comment]
According to https://cla.developers.google.com/clas I do have it signed, interesting.

**Pull request merged**
