### PR TITLE
Sigmah added as another Real world project

### PR DESCRIPTION
**Pull request by osarrat**
This change is [Reviewable](https://reviewable.io/reviews/gwtproject/gwt-site/182)

### CODE REVIEW

**Comment by osarrat** [comment]
I have just signed the CLA.

**Comment by jDramaix** [comment]
It seems there is still a problem with the CLA. Could you check here: https://cla.developers.google.com/clas that your github account is correct ?

**Comment by jDramaix** [comment]
LGTM and can be merged once the CLA issue has been resolved.

**Comment by osarrat** [comment]
I confirm that the provided GitHub account https://github.com/osarrat/ is the correct one.
Is the CLA issue coming from my email address ?
I don't use my gmail as contact address in Github.

**Comment by jDramaix** [comment]
> If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address. Check your existing CLA data and verify that your email is set on your git commits.

That should be the problem

**Comment by osarrat** [comment]
Ok, I have added my gmail as secondary Github email address. Tell me if that fixes the CLA issue.

**Comment by osarrat** [comment]
up

**Comment by osarrat** [comment]
Thanks @jDramaix for merging !
One question: when will this change be applied on the website online ?

**Comment by tbroyer** [comment]
ASAP. Julien is working on updating the site for the 2.8.0-rc1 release but AFAIK there have been backwards-incompatible changes in the GAE API that require updating https://gwt.googlesource.com/gwt-site-uploader/

**Comment by osarrat** [comment]
Thanks @tbroyer for your reply !

**Pull request merged**
